apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: 'true'
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway1
          image: python:3.10-slim
          command: ["/bin/sh","-c"]
          args:
            - |
              apt-get update && apt-get install -y git && \
              git clone git@github.com:SeEngel/mykubernetes.git /path/to/clone/directory && \
              pip install -r /mykubernetes/Gateway/requirements.txt && \
              mitmdump -s /mykubernetes/Gateway/app.py -p 8000 --listen-host 0.0.0.0
          resources:
            requests:
              cpu: '1'
              memory: 1Gi
            limits:
              cpu: '1'
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gateway-route
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    haproxy.router.openshift.io/timeout: 60s
spec:
  host: gateway.apps.cluster.intel.sandbox1234.opentlc.com
  to:
    kind: Service
    name: gateway-service
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
  wildcardPolicy: None

