name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Gateway/Dockerfile --tag gateway:$(date +%s)
    - name: Tag the Docker image
      run: docker tag gateway:$(date +%s) your-dockerhub-username/gateway:latest
    - name: Push the Docker image
      run: docker push your-dockerhub-username/gateway:latest
